using UnityEngine;
using System.Collections;
using UnityEngine.SceneManagement;
using UnityEngine.UI;

public class LoadingManager : MonoBehaviour
{
    private static LoadingManager _instance;
    public static LoadingManager Instance
    {
        get
        {
            if (_instance == null)
            {
                _instance = FindFirstObjectByType<LoadingManager>();

                if (_instance == null)
                {
                    GameObject go = new GameObject("LoadingManager_AutoGenerated");
                    _instance = go.AddComponent<LoadingManager>();
                }
            }
            return _instance;
        }
    }

    private Slider progressBar;

    private void Awake()
    {
        if (_instance == null)
        {
            _instance = this;
            DontDestroyOnLoad(gameObject);
        }
        else if (_instance != this)
        {
            Destroy(gameObject);
        }
    }

    public IEnumerator LoadScene()
    {
        AsyncOperation op = SceneManager.LoadSceneAsync("LoadingScene", LoadSceneMode.Additive);
        
        while (!op.isDone)
        {
            yield return null;
        }


        progressBar = FindFirstObjectByType<Slider>();
    }

    public void UnloadLoadingScreen()
    {
        if (SceneManager.GetSceneByName("LoadingScene").isLoaded)
        {
            SceneManager.UnloadSceneAsync("LoadingScene");
            PickaxeShop.IsAnyShopOpen = false;
        }
    }

    public void UpdateProgress(float progress)
    {
        if (progressBar != null) progressBar.value = progress;
    }
}